### ISSUE TITLE
clean-up of redundant code, re-factoring

### ISSUE THREAD

**Issue by nfarabullini** [miraisolutions/compareWith#1]
Assess the desirable degree of modularization and re-factor accordingly

**Comment by riccardoporreca** [comment]
Note that a considerable amount of modularity came through #6 and #2.

**Comment by riccardoporreca** [comment]
More, major re-factoring as part #8 (see PR #25)

**Comment by RolandASc** [comment]
@riccardoporreca I suppose we can now close this along with #8 ?

**Comment by riccardoporreca** [comment]
> @riccardoporreca I suppose we can now close this along with #8 ?

Fine with me

**Comment by nfarabullini** [comment]
core has been cleaned up through other issues
