### ISSUE TITLE
Check Meld installation / version on package load

### ISSUE THREAD

**Issue by nfarabullini** [miraisolutions/compareWith#3]
`.onLoad()` function to message the version of meld or warn about its absence if not installed.

See [Load hooks](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Load-hooks), `help(".onLoad")` for general information about the `.onLoad()` function.
> By convention, .onLoad() and friends are usually saved in a file called zzz.R
[[source](http://r-pkgs.had.co.nz/r.html)]

We need to check the behavior of `status <- system2("meld", "--version")` across platforms to make sure we have cover cases in a robust and consistent way. Three cases to assess (see also `help("system2")`)

A) Meld is installed and the version is printed to `stdout` => `(status <- system2("meld", "--version"))`
B) Meld is not installed => mimic as `(status <- system2("me_ld", "--version"))`
C) Meld is installed but somehow called with `--version` causes errors  => mimic as `(status <- system2("meld", "--ver_sion"))`

| Case | `stdout` | Warning? | `status` (error code) | `.onLoad()` logic|
|------|------|------|------|------|
| A | {MELD VERSION} | No | `0` (success) | - |
| B | - | Yes | `127` (could not run) | Suppress warning. stop: Meld is not installed or not added to the path environment variable. Point to installation instructions/README. |
| C | Meld's error output | Yes | >`0`, != `127` (exit status of `meld`) | Suppress warning. stop: Existing Meld is not working correctly. Make sure your Meld installation is fully functional and follow instructions on...(point to installation instructions/README). |

If, as hinted below, we would use `stdout = TRUE` (and `stderr = TRUE` since the two cannot be really separated), the returned `status` is a character vector and the behavior would be

| Case | Condition | `status` (stdout) |
|------|------|------|
| A | - | {MELD VERSION} |
| B | Error | - |
| C | Warning | Meld's error output, with the exit status of `meld` as `attr(,"status")`|

R Markdown [check_meld_version.Rmd](https://github.com/miraisolutions/compareWith/files/3174194/check_meld_version.Rmd.txt) for testing (to be renamed as `.Rmd` only, w/o the extra `.txt`)

- [x] Ubuntu => The _nominal_ version of meld installed via `apt` (3.18.0) does not cause any issues. The only difference wrt Windows is that error messages in Case B are more generic => R Mardkown output:  
[check_meld_version_ubuntu.pdf](https://github.com/miraisolutions/compareWith/files/3181466/check_meld_version_ubuntu.pdf)

- [x] Windows => Meld 3.20.0 seems to have issues with many Gtk warnings in the `stdout`. Issues disappear using the **Meld 3.18.3** installer (as hinted on Meld's website, we should probably mention this in the package README), and the behaviour is consistent with the table above => R Mardkown output: [check_meld_version_win.zip](https://github.com/miraisolutions/compareWith/files/3174203/check_meld_version_win.zip)

- [x] macOS => **Meld 3.19.0** crashes. **Meld 3.16.0** works pretty smoothly => R Mardkown output: 
[check_meld_mac.pdf](https://github.com/miraisolutions/compareWith/files/3191379/check_meld_mac.pdf)

**Comment by riccardoporreca** [comment]
See also comments in #5 about hinting how to install Meld similar to what done in other packages.

**Comment by RolandASc** [comment]
ok, but just to add/clarify, I'd still throw an error if it's not detected upon load, even if we let the installation fail in #5 (it could always happen that someone loses `meld` later on)

**Comment by riccardoporreca** [comment]
> ok, but just to add/clarify, I'd still throw an error if it's not detected upon load, even if we let the installation fail in #5 (it could always happen that someone loses `meld` later on)

Absolutely, this is the main goal of this issue. Note that an error upon load (`.onLoad()` function) also prevents a package from being successfully installed (failing on `testing if installed package can be loaded`)

**Comment by riccardoporreca** [comment]
Re-opening due to unsuccessful `R CMD check`.
It is probably a good time to add Travis CI.

**Comment by riccardoporreca** [comment]
See

**Comment by riccardoporreca** [comment]
Added unit-tests for the three cases using the same approach as [check_meld_version.Rmd](https://github.com/miraisolutions/compareWith/files/3174194/check_meld_version.Rmd.txt).
