### ISSUE TITLE
Install from github repo fails on Win7, R 3.6.0 or 3.6.1 (64-bit)

### ISSUE THREAD

**Issue by jmcastagnetto** [miraisolutions/compareWith#30]
```
> remotes::install_github("miraisolutions/compareWith")
Downloading GitHub repo miraisolutions/compareWith@master
Error: Failed to install 'compareWith' from GitHub:
  Incorrect number of arguments (16), expecting 14 for 'processx_exec'
```

**Comment by jmcastagnetto** [comment]
FYI - no problem on Ubuntu 18.04 LTS, with R 3.6.1 64-bit.

On Win7, retried after installing meld 3.18.3 (removed 3.20.0 first). That is not the issue. Got same error.

**Comment by jmcastagnetto** [comment]
OK, problem tracked to the [processx](https://github.com/r-lib/processx) package.

After doing a:

```
> install.package("processx")
```

which got version 3.4.0, now everything works on Win7

**Comment by nfarabullini** [comment]
Glad it worked. Thanks for the info :+1
