### ISSUE TITLE
Only one of Compare with... / Compare with neighbor...

### ISSUE THREAD

**Issue by riccardoporreca** [miraisolutions/compareWith#8]
The RStudio Addins menu can easily get very long, so we should try to limit the number of addins.

The existing "Compare with..." / "Compare with neighbor..." only differ by the starting folder of the file browser being the directory / file location. Do we really need both of them? I think it is fine to have a single addin "Compare with...", using the location of the current file as a starting point, from which it is easy to navigate e.g. up to the project directory.

- [x] Agree on the addins
    - Keep only "Compare with other...", with same behavior as former "Compare with neighbor..."
- [x] Agree on the order and names of the addins (shown in the RStudio Addins menu)
    1. Compare with repo
    1. Compare with repo - project
    1. Compare with other...
- [x] Re-create the animated GIF in the README (#9)
    - See c10b0c5 and f89f9161923ba6a40285970a7f283c50e4cc98a7

**Comment by riccardoporreca** [comment]
As discussed with @RolandASc  and @nfarabullini, we will go for a single addin "Compare with other..." using the location of the current file. The corresponding binding `compare_with_other()` will wrap around a function, e.g. `compare_with(...)`, having arguments for a flexible behavior.

**Comment by riccardoporreca** [comment]
Initial commit ef71bde, with function `compare_with()` implementing the flexible comparison of files:

- Current file vs. explicit path
- Version control comparison vs. against second file searched in same or current directory.
- Used by `compare_with_other()` and `compare_with_repo()`

**Comment by riccardoporreca** [comment]
As discussed, we want to have the following as the only exported functions:
- `compare_with_other(path, location)`
- `compare_with_repo(path)`
- `compare_active_file_with_other(location)`
- `compare_active_file_with_repo()`
- `compare_project_with_repo()`

The addins bindings should be unexported (existing help page only documenting the addins), and have short names:
- `:::compare_repo()`
- `:::compare_project()`
- `:::compare_other()`

Refactoring should be done to support generic comparison of files and directories (`path`), and to allow customizing error messages only for the addins.

**Comment by riccardoporreca** [comment]
Note that consistency of addins definition, documentation, and custom error messages is fully guaranteed via

- Dynamically documenting the addin name and description based on `addins.dcf`
- Unit tests for checking the existence of binding functions specified in `addins.dcf` and the correctness of the addin name used when customizing the messages.

**Comment by RolandASc** [comment]
@riccardoporreca I suppose we can close this then?

**Comment by riccardoporreca** [comment]
> @riccardoporreca I suppose we can close this then?

Indeed, there was no `closes` in any of the commit nor in the PR, but this was meant to get closed upon ,erging #25
